package org.chenile.core.event;

import org.chenile.core.annotation.ChenileAnnotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

/**
 * Allows service-operations to subscribe to named events.
 * Events can be generated by multiple Chenile Modules (such as filewatcher, chenile-pub-sub, scheduler etc.)
 */
@ChenileAnnotation
@Retention(RUNTIME)
@Target(ElementType.TYPE)
public @interface SubscribeTo {
    public String value();
}
